<a href="https://colab.research.google.com/github/furkancimen/COT5600/blob/master/COT5600_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from scipy.linalg import null_space
import pdb

def annihilate_poly(M):
  M = np.array(M)
  size = M.shape
  #  Check for proper Matrix dimensions
  if len(size) != 2:
    print('Please enter a proper square matrix')
    exit(0)
  elif size[0] != size[1]:
    print('Matrix shpuld be a square matrix')
    exit(0)
  n = size[0] # the size of matrix
  M_power = np.identity(n)
  M_vec = np.zeros(shape=(n**2, n**2 + 1)) # max vec size to have a guaranteed solution other than non-trivial
  for i in range(n**2+1):
    M_vec[:,i] = M_power.flatten()
    M_power = np.matmul(M_power, M)

  null_s = null_space(M_vec) # Gets the null space
  #print(np.allclose(M_vec.dot(null_s), 0))  # Checks the null space solution is ok
  return null_s[:,0] # returns just the first vector from the null space

def annihilate_min_deg_poly(M):
  M = np.array(M)
  size = M.shape
  #  Check for proper Matrix dimensions
  if len(size) != 2:
    print('Please enter a proper square matrix')
    exit(0)
  elif size[0] != size[1]:
    print('Matrix shpuld be a square matrix')
    exit(0)
  n = size[0] # the size of matrix
  M_power = np.identity(n)
  M_vec = np.zeros(shape=(n**2, n**2 + 1)) # max vec size to have a guaranteed solution other than non-trivial
  for i in range(n**2+1):
    M_vec[:,i] = M_power.flatten()
    M_power = np.matmul(M_power, M)
    null_s = null_space(M_vec[:, 0:i+1]) # Gets the null space
    if null_s.any():  # If there is a non-trivial solution for null-space it ends the for loop
      # print(null_s)
      break
  
  #print(np.allclose(M_vec[:, 0:i+1].dot(null_s), 0))  # Checks the null space solution is ok
  return null_s[:,0] # returns just the first vector from the null space

def test_of_annihilation(input_matrix, annihilation_vector):
  print('\nThis is the coefficients for annihilation\n', annihilation_vector, sep='')
  # test starts
  n = input_matrix.shape[0] # the size of input matrix
  M_power = np.identity(n) # The zero power of every matrix is identity
  M_annihilate = 0  # Powers of matrix is going to be added to this matrix and at the end it needs to be completely zero
  for i in range(len(annihilation_vector)):
    M_annihilate += M_power * annihilation_vector[i]
    M_power = np.matmul(M_power, input_matrix)
  print('\nAnnihilation result\n',M_annihilate, sep='')
  print('\nIs the annihilated matrix is zero or close enough to zero? ==> ',
        np.allclose(M_annihilate, 0), sep='') # Checks the annihilate vector is close enough to zero to be considered zero



input_matrix = np.array([[1,0], [0,1]])

# an example to test annihilate_poly
print('\n', '*'*10, 'Test of annihilate_poly', '*'*10)
annihilation_vector = annihilate_poly(input_matrix)
test_of_annihilation(input_matrix, annihilation_vector)

# an example to test annihilate_min_deg_poly
print('\n', '*'*10, 'Test of annihilate_min_deg_poly', '*'*10)
annihilation_vector = annihilate_min_deg_poly(input_matrix)
test_of_annihilation(input_matrix, annihilation_vector)




 ********** Test of annihilate_poly **********

This is the coefficients for annihilation
[ 0.37115547  0.88506757 -0.25317143  0.12005823 -0.01972954]

Annihilation result
[[8.88178420e-16 1.77635684e-15]
 [3.55271368e-15 3.55271368e-15]]

Is the annihilated matrix is zero or close enough to zero? ==> True

 ********** Test of annihilate_min_deg_poly **********

This is the coefficients for annihilation
[-0.36514837 -0.91287093  0.18257419]

Annihilation result
[[-1.99840144e-15 -2.22044605e-16]
 [-4.44089210e-16 -1.77635684e-15]]

Is the annihilated matrix is zero or close enough to zero? ==> True
