<a href="https://colab.research.google.com/github/furkancimen/COT5600/blob/master/hw_1/COT5600_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
from scipy.linalg import null_space
import pdb

def annihilate_poly(M):
  M = np.array(M)
  size = M.shape
  #  Check for proper Matrix dimensions
  if len(size) != 2:
    print('Please enter a proper square matrix')
    exit(0)
  elif size[0] != size[1]:
    print('Matrix shpuld be a square matrix')
    exit(0)
  n = size[0] # the size of matrix
  M_power = np.identity(n)
  M_vec = np.zeros(shape=(n**2, n**2 + 1)) # max vec size to have a guaranteed solution other than non-trivial
  for i in range(n**2+1):
    M_vec[:,i] = M_power.flatten()
    M_power = np.matmul(M_power, M)

  null_s = null_space(M_vec) # Gets the null space
  #print(np.allclose(M_vec.dot(null_s), 0))  # Checks the null space solution is ok
  return null_s[:,0] # returns just the first vector from the null space

def annihilate_min_deg_poly(M):
  M = np.array(M)
  size = M.shape
  #  Check for proper Matrix dimensions
  if len(size) != 2:
    print('Please enter a proper square matrix')
    exit(0)
  elif size[0] != size[1]:
    print('Matrix shpuld be a square matrix')
    exit(0)
  n = size[0] # the size of matrix
  M_power = np.identity(n)
  M_vec = np.zeros(shape=(n**2, n**2 + 1)) # max vec size to have a guaranteed solution other than non-trivial
  for i in range(n**2+1):
    M_vec[:,i] = M_power.flatten()
    M_power = np.matmul(M_power, M)
    null_s = null_space(M_vec[:, 0:i+1]) # Gets the null space
    if null_s.any():  # If there is a non-trivial solution for null-space it ends the for loop
      # print(null_s)
      break
  
  #print(np.allclose(M_vec[:, 0:i+1].dot(null_s), 0))  # Checks the null space solution is ok
  return null_s[:,0] # returns just the first vector from the null space

def test_of_annihilation(input_matrix, annihilation_vector):
  print('\nThis is the coefficients for annihilation\n', annihilation_vector, sep='')
  # test starts
  n = input_matrix.shape[0] # the size of input matrix
  M_power = np.identity(n) # The zero power of every matrix is identity
  M_annihilate = 0  # Powers of matrix is going to be added to this matrix and at the end it needs to be completely zero
  for i in range(len(annihilation_vector)):
    M_annihilate += M_power * annihilation_vector[i]
    M_power = np.matmul(M_power, input_matrix)
  print('\nAnnihilation result\n',M_annihilate, sep='')
  print('\nIs the annihilated matrix is zero or close enough to zero? ==> ',
        np.allclose(M_annihilate, 0), sep='') # Checks the annihilate vector is close enough to zero to be considered zero



# First examples to check the difference between annihilate_poly and annihilate_min_deg_poly
# Min polynamial degree should be third degree
input_matrix = np.array([[1,0,0], [0,2,0], [0,0,4]])
print('Min polynamial degree should be third degree by fallowing input')
print('Input matrix\n', input_matrix)

# an example to test annihilate_poly
print('\n', '*'*10, 'Test of annihilate_poly', '*'*10)
annihilation_vector = annihilate_poly(input_matrix)
test_of_annihilation(input_matrix, annihilation_vector)

# an example to test annihilate_min_deg_poly
print('\n', '*'*10, 'Test of annihilate_min_deg_poly', '*'*10)
annihilation_vector = annihilate_min_deg_poly(input_matrix)
test_of_annihilation(input_matrix, annihilation_vector)

# Second examples to check the difference between annihilate_poly and annihilate_min_deg_poly
# As input multiple of identity min degree polinamial should be first degree
input_matrix = np.array([[5,0,0], [0,5,0], [0,0,5]])
print('\n','%'*90, '\n')
print('As input multiple of identity min degree polinamial should be first degree')
print('Input matrix\n', input_matrix)

# an example to test annihilate_poly
print('\n', '*'*10, 'Test of annihilate_poly', '*'*10)
annihilation_vector = annihilate_poly(input_matrix)
test_of_annihilation(input_matrix, annihilation_vector)

# an example to test annihilate_min_deg_poly
print('\n', '*'*10, 'Test of annihilate_min_deg_poly', '*'*10)
annihilation_vector = annihilate_min_deg_poly(input_matrix)
test_of_annihilation(input_matrix, annihilation_vector)



Min polynamial degree should be third degree by fallowing input
Input matrix
 [[1 0 0]
 [0 2 0]
 [0 0 4]]

 ********** Test of annihilate_poly **********

This is the coefficients for annihilation
[ 0.21273423  0.41560632  0.20005075 -0.59008767 -0.15647002 -0.43443796
  0.17938245  0.33560715 -0.187442    0.02505673]

Annihilation result
[[-3.67761377e-16  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -3.55271368e-15  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.81898940e-12]]

Is the annihilated matrix is zero or close enough to zero? ==> True

 ********** Test of annihilate_min_deg_poly **********

This is the coefficients for annihilation
[ 0.45436947 -0.79514657  0.39757328 -0.05679618]

Annihilation result
[[-4.99600361e-16  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.77635684e-15  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.99360578e-15]]

Is the annihilated matrix is zero or close enough to zero? ==> True

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%